// Generated by CoffeeScript 1.6.3
(function() {
  var $, Page, defaultConfig;

  $ = jQuery;

  Page = function(target, opts) {
    this.target = target;
    this.opts = opts;
    this.currPage = opts.defPage;
    return this.init();
  };

  Page.prototype = {
    init: function() {
      var opts, that, tmp, wrap;
      that = this;
      opts = that.opts;
      tmp = that.createPage(opts.defPage);
      wrap = that.pageWrap = $('<div></div>');
      wrap.addClass(opts.pageWrapClass);
      wrap.html(tmp);
      that.target.after(wrap);
      that.p;
      that.bindEvent();
    },
    createPage: function(curPage) {
      var nHide, opts, pHide, tagFirst, tagLast, tagString, tags, that;
      that = this;
      opts = that.opts;
      tags = opts.tags;
      pHide = nHide = '';
      if (curPage <= 1) {
        pHide = 'hide';
      }
      if (curPage >= opts.total) {
        nHide = 'hide';
      }
      tagFirst = "<" + tags + " data-n=\"1\" class=\"first\">首页</" + tags + ">";
      tagString = "<" + tags + " class=\"prev " + pHide + "\">上一页</" + tags + ">";
      for (var i=0; i<opts.total; i++){
			var cla = '';
			if((i+1) === curPage){
				cla = opts.curClass
			}
			tagString += '<' + tags + ' data-n="'+(i+1)+'" class="' + cla + '">' + (i+1) + '</'+tags+'>';
		};
      tagString += "<" + tags + " class=\"next " + nHide + "\">下一页</" + tags + ">		";
      tagLast = "<" + tags + " data-n=\"" + opts.total + "\" class=\"last\">尾页</" + tags + ">";
      if (opts.first) {
        tagString = tagFirst + tagString;
      }
      if (opts.last) {
        tagString += tagLast;
      }
      return tagString;
    },
    getIndex: function(obj) {
      var index;
      index = this.currPage;
      if (obj.hasClass('next')) {
        index++;
        if (index > this.opts.total) {
          return false;
        }
      } else if (obj.hasClass('prev')) {
        index--;
        if (index < 1) {
          return false;
        }
      } else {
        index = obj.attr('data-n');
      }
      return index | 0;
    },
    pNSH: function(index) {
      var pageWrap;
      pageWrap = this.pageWrap;
      if (index <= 1) {
        pageWrap.find('.prev').addClass('hide');
        pageWrap.find('.next').removeClass('hide');
        return;
      } else if (index >= this.opts.total) {
        pageWrap.find('.next').addClass('hide');
        pageWrap.find('.prev').removeClass('hide');
        return;
      }
      pageWrap.find('.next').removeClass('hide');
      pageWrap.find('.prev').removeClass('hide');
    },
    bindEvent: function() {
      var opts, that;
      that = this;
      opts = that.opts;
      that.pageWrap.delegate(opts.tags, 'click', function() {
        var index, _this;
        _this = $(this);
        index = that.getIndex(_this);
        if (typeof index !== 'number') {
          return index;
        }
        that.pNSH(index);
        that.currPage = index;
        that.pageWrap.children().eq(1 + index).addClass(opts.curClass).siblings().removeClass(opts.curClass);
        opts.callback && opts.callback(index);
      });
    }
  };

  defaultConfig = {
    tags: 'em',
    pageWrapClass: 'pagenav',
    curClass: 'current',
    first: true,
    last: true,
    defPage: 1,
    total: 5,
    callback: function() {}
  };

  $.fn.pageNav = function(opts) {
    opts = $.extend({}, defaultConfig, opts);
    new Page($(this), opts);
  };

}).call(this);
