// Generated by CoffeeScript 1.6.3
(function() {
  var $, Page, defaultConfig;

  $ = jQuery;

  Page = function(target, opts) {
    this.target = target;
    this.opts = opts;
    this.currPage = opts.defPage;
    return this.init();
  };

  Page.prototype = {
    init: function() {
      var opts, that, wrap;
      that = this;
      opts = that.opts;
      wrap = that.pageWrap = $('<div></div>');
      wrap.addClass(opts.pageWrapClass);
      that.createPage(opts.defPage);
      that.target.after(wrap);
      that.p;
      that.bindEvent();
    },
    createPage: function(curPage) {
      var arr, i, len, opts, page, tags, that, total;
      that = this;
      opts = that.opts;
      tags = opts.tags;
      total = opts.total * 1 || 1;
      curPage = curPage * 1 || 1;
      page = total > 100 ? 2 : 4;
      len = curPage + page > total ? total : curPage + page;
      i = curPage - page < 1 ? 1 : curPage - page;
      arr = ['<em class="prev">\u4e0a\u4e00\u9875</em>'];
      if (curPage - page > 2) {
        arr.push('<em data-n="1">1</em><em class="no"> ... </em>');
      } else if (curPage - page === 2) {
        arr.push('<em data-n="1">1</em>');
      }
      for(;i <= len; i++){
			if (i == curPage){
				arr.push('<em data-n="'+i+'" class="current">'+i+'</em>')
			}else{
				arr.push('<em data-n="'+i+'">'+i+'</em>')
			}
		};
      if (curPage + page < total - 1) {
        arr.push("<em class=\"no\"> ... </em><em data-n=\"" + total + "\">" + total + "</em>");
      } else if (curPage + page === total - 1) {
        arr.push("<em data-n=\"" + total + "\">" + total + "</em>");
      }
      arr.push('<em class="next">\u4e0b\u4e00\u9875</em>');
      return that.pageWrap.html(arr.join(''));
    },
    getIndex: function(obj) {
      var index;
      index = this.currPage;
      if (obj.hasClass('next')) {
        index++;
        if (index > this.opts.total) {
          return false;
        }
      } else if (obj.hasClass('prev')) {
        index--;
        if (index < 1) {
          return false;
        }
      } else {
        index = obj.attr('data-n');
      }
      return index | 0;
    },
    bindEvent: function() {
      var opts, that;
      that = this;
      opts = that.opts;
      that.pageWrap.delegate(opts.tags, 'click', function() {
        var index, _this;
        _this = $(this);
        index = that.getIndex(_this);
        if (typeof index !== 'number') {
          return index;
        }
        that.currPage = index;
        that.createPage(index);
        opts.callback && opts.callback(index);
      });
    }
  };

  defaultConfig = {
    tags: 'em',
    pageWrapClass: 'pagenav',
    curClass: 'current',
    defPage: 1,
    total: 5,
    callback: function() {}
  };

  $.fn.pageNav = function(opts) {
    opts = $.extend({}, defaultConfig, opts);
    new Page($(this), opts);
  };

}).call(this);
